name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  TF_VAR_AWS_REGION: 'us-east-2'

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        python-version: 3.9
    - name: Install AWS CLI
      run: pip install awscli

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: apply 00-bootstrap
      working-directory: 00-bootstrap
      run: |
        aws s3 cp s3://sls-terraform-statefiles/00-bootstrap.tfstate .
        terraform init
        terraform plan

  common:
    runs-on: ubuntu-latest
    needs: bootstrap
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        python-version: 3.9
    - name: Install AWS CLI
      run: pip install awscli

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: apply 01-common
      working-directory: 01-common
      run: |
        terraform init
        terraform plan

  dev:
    runs-on: ubuntu-latest
    needs: common
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        python-version: 3.9
    - name: Install AWS CLI
      run: pip install awscli

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: apply dev
      working-directory: dev
      run: |
        terraform init
        terraform plan

  stage:
    runs-on: ubuntu-latest
    needs: dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        python-version: 3.9
    - name: Install AWS CLI
      run: pip install awscli

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: apply stage
      working-directory: stage
      run: |
        terraform init
        terraform plan

#    - name: Apply Terraform
#      run: terraform apply -auto-approve

