name: Terraform Workflow

on:
  push:
    branches:
      - main

env:
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  TF_VAR_AWS_REGION: 'us-east-2'

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [00-bootstrap, 01-common, dev, stage]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        python-version: 3.9
    - name: Install AWS CLI
      run: pip install awscli

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.5

    - name: Initialize Terraform
      working-directory: ${{ matrix.env }}
      run: |
        aws s3 ls
        terraform init

    - name: Plan Terraform
      working-directory: ${{ matrix.env }}
      run: terraform plan

#    - name: Apply Terraform
#      run: terraform apply -auto-approve

